local ECLIPSE_FALL_SPELL = "ECLIPSE_FALL"
local ECLIPSE_FALL_DURABILITY_COST_PCT = .05
local ECLIPSE_FALL_LV2_EXTRA_DURABILITY_COST_PCT = .05
local ECLIPSE_FALL_COOLDOWN_ID = "eclipse_fall"
local ECLIPSE_FALL_COOLDOWN_TIME = 30
local ECLIPSE_FALL_ICON_SCALE = .72
local ECLIPSE_FALL_ICON_RADIUS = 58
local ECLIPSE_FALL_CAST_RANGE = 12

-- Small meteors: 18 shots spread evenly over the duration.
local ECLIPSE_FALL_SMALL_COUNT = 18
local ECLIPSE_FALL_SMALL_DURATION = 3.0
-- Large meteor (Lv2): starts its warning exactly when the small barrage ends.
local ECLIPSE_FALL_LARGE_WARNING_DELAY = 3.0

local ECLIPSE_FALL_DAMAGE_SMALL = 7
local ECLIPSE_FALL_DAMAGE_LARGE = 28
local ECLIPSE_FALL_DAMAGE_PER_SANITY = .01
local ECLIPSE_FALL_DARK_SCHOLAR_SANITY_DISCOUNT = .10
-- Max sanity counted for damage scale (200 waxwell base + 75 CI); cost still spends full current.
local ECLIPSE_FALL_MAX_SANITY_SCALE = 275

-- Meteor scale/range: small = vanilla small × SMALL_SIZE_MULT | large = vanilla large × LARGE_SIZE_MULT.
local ECLIPSE_FALL_VANILLA_SMALL_SIZE = .7
local ECLIPSE_FALL_VANILLA_LARGE_SIZE = 1.3
local ECLIPSE_FALL_SMALL_SIZE_MULT = 1.4
local ECLIPSE_FALL_LARGE_SIZE_MULT = 1.6
local ECLIPSE_FALL_LARGE_SHAKE_MULT = 1.2
-- Large meteor ground scorch only: ×0.8 (~20% smaller than the default large formula).
local ECLIPSE_FALL_LARGE_SCORCH_MULT = 0.8
local ECLIPSE_FALL_SCORCH_VANILLA_MULT = 1.3
local ECLIPSE_FALL_SOUND_VOLUME = 0.8
-- Meteor visual: darken ~80% (RGB mult 0.2) on body + ground warning.
local ECLIPSE_FALL_METEOR_TINT_MULT = 0.2

-- Reticule: reticule_l1 (large anim, scale 1) — small meteors random inside this work radius.
local ECLIPSE_FALL_RETICULE_SCALE = 1
local ECLIPSE_FALL_RETICULE_WORK_RADIUS = ECLIPSE_FALL_RETICULE_SCALE * 8
local ECLIPSE_FALL_METEOR_RADIUS = 3.5
local ECLIPSE_FALL_WARN_TIME = 1.0
local ECLIPSE_FALL_STRIKE_ANIM_DELAY = .33

-- Lv2 ice spikes (deerclops small icespike) — 8 directions × 5 tiers from large meteor center.
local ECLIPSE_FALL_SPIKE_DIRECTION_COUNT = 8
local ECLIPSE_FALL_SPIKE_TIER_COUNT = 5
local ECLIPSE_FALL_SPIKE_ANGLE_SPREAD = 30 * DEGREES
local ECLIPSE_FALL_SPIKE_DAMAGE = 3
local ECLIPSE_FALL_SPIKE_IMPACT_RADIUS = 1.25
-- First tier slightly sooner after large meteor impact; keep 0.10s between tiers.
local ECLIPSE_FALL_SPIKE_TIER_DELAYS = { .04, .14, .24, .34, .44 }
local ECLIPSE_FALL_SPIKE_TIER_DISTANCES = { 1.50, 2.50, 3.50, 4.50, 5.50 }
local ECLIPSE_FALL_SPIKE_SOUND_VOLUME = 0.5
-- Spike visual: darken ~90% (RGB mult 0.1).
local ECLIPSE_FALL_SPIKE_TINT_MULT = 0.1

local IMPACT_EXCLUDE_TAGS = { "INLIMBO", "playerghost", "FX", "NOCLICK", "DECOR", "meteor_protection", "wall", "structure" }

return {
    ECLIPSE_FALL_SPELL = ECLIPSE_FALL_SPELL,
    ECLIPSE_FALL_DURABILITY_COST_PCT = ECLIPSE_FALL_DURABILITY_COST_PCT,
    ECLIPSE_FALL_LV2_EXTRA_DURABILITY_COST_PCT = ECLIPSE_FALL_LV2_EXTRA_DURABILITY_COST_PCT,
    ECLIPSE_FALL_COOLDOWN_ID = ECLIPSE_FALL_COOLDOWN_ID,
    ECLIPSE_FALL_COOLDOWN_TIME = ECLIPSE_FALL_COOLDOWN_TIME,
    ECLIPSE_FALL_ICON_SCALE = ECLIPSE_FALL_ICON_SCALE,
    ECLIPSE_FALL_ICON_RADIUS = ECLIPSE_FALL_ICON_RADIUS,
    ECLIPSE_FALL_CAST_RANGE = ECLIPSE_FALL_CAST_RANGE,
    ECLIPSE_FALL_SMALL_COUNT = ECLIPSE_FALL_SMALL_COUNT,
    ECLIPSE_FALL_SMALL_DURATION = ECLIPSE_FALL_SMALL_DURATION,
    ECLIPSE_FALL_LARGE_WARNING_DELAY = ECLIPSE_FALL_LARGE_WARNING_DELAY,
    ECLIPSE_FALL_DAMAGE_SMALL = ECLIPSE_FALL_DAMAGE_SMALL,
    ECLIPSE_FALL_DAMAGE_LARGE = ECLIPSE_FALL_DAMAGE_LARGE,
    ECLIPSE_FALL_DAMAGE_PER_SANITY = ECLIPSE_FALL_DAMAGE_PER_SANITY,
    ECLIPSE_FALL_DARK_SCHOLAR_SANITY_DISCOUNT = ECLIPSE_FALL_DARK_SCHOLAR_SANITY_DISCOUNT,
    ECLIPSE_FALL_MAX_SANITY_SCALE = ECLIPSE_FALL_MAX_SANITY_SCALE,
    ECLIPSE_FALL_VANILLA_SMALL_SIZE = ECLIPSE_FALL_VANILLA_SMALL_SIZE,
    ECLIPSE_FALL_VANILLA_LARGE_SIZE = ECLIPSE_FALL_VANILLA_LARGE_SIZE,
    ECLIPSE_FALL_SMALL_SIZE_MULT = ECLIPSE_FALL_SMALL_SIZE_MULT,
    ECLIPSE_FALL_LARGE_SIZE_MULT = ECLIPSE_FALL_LARGE_SIZE_MULT,
    ECLIPSE_FALL_LARGE_SHAKE_MULT = ECLIPSE_FALL_LARGE_SHAKE_MULT,
    ECLIPSE_FALL_LARGE_SCORCH_MULT = ECLIPSE_FALL_LARGE_SCORCH_MULT,
    ECLIPSE_FALL_SCORCH_VANILLA_MULT = ECLIPSE_FALL_SCORCH_VANILLA_MULT,
    ECLIPSE_FALL_SOUND_VOLUME = ECLIPSE_FALL_SOUND_VOLUME,
    ECLIPSE_FALL_METEOR_TINT_MULT = ECLIPSE_FALL_METEOR_TINT_MULT,
    ECLIPSE_FALL_RETICULE_SCALE = ECLIPSE_FALL_RETICULE_SCALE,
    ECLIPSE_FALL_RETICULE_WORK_RADIUS = ECLIPSE_FALL_RETICULE_WORK_RADIUS,
    ECLIPSE_FALL_METEOR_RADIUS = ECLIPSE_FALL_METEOR_RADIUS,
    ECLIPSE_FALL_WARN_TIME = ECLIPSE_FALL_WARN_TIME,
    ECLIPSE_FALL_STRIKE_ANIM_DELAY = ECLIPSE_FALL_STRIKE_ANIM_DELAY,
    ECLIPSE_FALL_SPIKE_DIRECTION_COUNT = ECLIPSE_FALL_SPIKE_DIRECTION_COUNT,
    ECLIPSE_FALL_SPIKE_TIER_COUNT = ECLIPSE_FALL_SPIKE_TIER_COUNT,
    ECLIPSE_FALL_SPIKE_ANGLE_SPREAD = ECLIPSE_FALL_SPIKE_ANGLE_SPREAD,
    ECLIPSE_FALL_SPIKE_DAMAGE = ECLIPSE_FALL_SPIKE_DAMAGE,
    ECLIPSE_FALL_SPIKE_IMPACT_RADIUS = ECLIPSE_FALL_SPIKE_IMPACT_RADIUS,
    ECLIPSE_FALL_SPIKE_TIER_DELAYS = ECLIPSE_FALL_SPIKE_TIER_DELAYS,
    ECLIPSE_FALL_SPIKE_TIER_DISTANCES = ECLIPSE_FALL_SPIKE_TIER_DISTANCES,
    ECLIPSE_FALL_SPIKE_SOUND_VOLUME = ECLIPSE_FALL_SPIKE_SOUND_VOLUME,
    ECLIPSE_FALL_SPIKE_TINT_MULT = ECLIPSE_FALL_SPIKE_TINT_MULT,
    IMPACT_EXCLUDE_TAGS = IMPACT_EXCLUDE_TAGS,
}
