local CHAOS_INOCULATION_EFFECTIVE_MAX_HEALTH = 1
local CHAOS_INOCULATION_EXTRA_SANITY = 75

return {
    CHAOS_INOCULATION_EFFECTIVE_MAX_HEALTH = CHAOS_INOCULATION_EFFECTIVE_MAX_HEALTH,
    CHAOS_INOCULATION_EXTRA_SANITY = CHAOS_INOCULATION_EXTRA_SANITY,
}
