STRINGS.SPELLS = STRINGS.SPELLS or {}
local SHADOW_LANTERNBEARER_SPELL = "SHADOW_LANTERNBEARER"
local SHADOW_LANTERNBEARER_ICON_SCALE = .6
local SHADOW_LANTERNBEARER_ICON_RADIUS = 50
local SHADOW_LANTERNBEARER_DURABILITY_COST_PCT = .05
-- reticule_l (large anim): work_radius = scale × 8
local SHADOW_LANTERNBEARER_RETICULE_SCALE = 1.5
local SHADOW_LANTERNBEARER_TARGET_WORK_RADIUS = SHADOW_LANTERNBEARER_RETICULE_SCALE * 8
local SHADOW_LANTERNBEARER_LV2_TAG = "shadow_lanternbearer_2"
local SHADOW_LANTERNBEARER_2_BASE_DURABILITY_COST_PCT = .05
local SHADOW_LANTERNBEARER_2_DURABILITY_COST_PCT = .10

return {
    SHADOW_LANTERNBEARER_SPELL = SHADOW_LANTERNBEARER_SPELL,
    SHADOW_LANTERNBEARER_ICON_SCALE = SHADOW_LANTERNBEARER_ICON_SCALE,
    SHADOW_LANTERNBEARER_ICON_RADIUS = SHADOW_LANTERNBEARER_ICON_RADIUS,
    SHADOW_LANTERNBEARER_DURABILITY_COST_PCT = SHADOW_LANTERNBEARER_DURABILITY_COST_PCT,
    SHADOW_LANTERNBEARER_RETICULE_SCALE = SHADOW_LANTERNBEARER_RETICULE_SCALE,
    SHADOW_LANTERNBEARER_TARGET_WORK_RADIUS = SHADOW_LANTERNBEARER_TARGET_WORK_RADIUS,
    SHADOW_LANTERNBEARER_LV2_TAG = SHADOW_LANTERNBEARER_LV2_TAG,
    SHADOW_LANTERNBEARER_2_BASE_DURABILITY_COST_PCT = SHADOW_LANTERNBEARER_2_BASE_DURABILITY_COST_PCT,
    SHADOW_LANTERNBEARER_2_DURABILITY_COST_PCT = SHADOW_LANTERNBEARER_2_DURABILITY_COST_PCT,
}
