local LETHAL_APPARITION_2_BASE_DURABILITY_COST_PCT = .05
local LETHAL_APPARITION_2_DURABILITY_COST_PCT = .10
local LETHAL_APPARITION_1_TAG = "lethal_apparition_1_shadow_duelist"
local LETHAL_APPARITION_2_TAG = "lethal_apparition_2_shadow_duelist"
local LETHAL_APPARITION_1_HEALTH = 100
local LETHAL_APPARITION_1_DURATION_BONUS_PCT = .50
local LETHAL_APPARITION_2_CRIT_CHANCE = .25
local LETHAL_APPARITION_2_CRIT_MULT = 1.50

return {
    LETHAL_APPARITION_2_BASE_DURABILITY_COST_PCT = LETHAL_APPARITION_2_BASE_DURABILITY_COST_PCT,
    LETHAL_APPARITION_2_DURABILITY_COST_PCT = LETHAL_APPARITION_2_DURABILITY_COST_PCT,
    LETHAL_APPARITION_1_TAG = LETHAL_APPARITION_1_TAG,
    LETHAL_APPARITION_2_TAG = LETHAL_APPARITION_2_TAG,
    LETHAL_APPARITION_1_HEALTH = LETHAL_APPARITION_1_HEALTH,
    LETHAL_APPARITION_1_DURATION_BONUS_PCT = LETHAL_APPARITION_1_DURATION_BONUS_PCT,
    LETHAL_APPARITION_2_CRIT_CHANCE = LETHAL_APPARITION_2_CRIT_CHANCE,
    LETHAL_APPARITION_2_CRIT_MULT = LETHAL_APPARITION_2_CRIT_MULT,
}
