local INNER_INCARNATE_FLAT_DAMAGE_PER_LEVEL = 2
local INNER_INCARNATE_PASSIVE_SHADOW_LEVEL = 1
local INNER_INCARNATE_LANTERN_SHADOW_LEVEL = 1
local INNER_INCARNATE_DAMAGE_REDUCTION_PER_LEVEL = .005
local INNER_INCARNATE_SANITY_REGEN_PER_LEVEL = 0.5 / 60 -- +0.5/min per shadow level
local INNER_INCARNATE_SUMMON_SLOT_PENALTY = 2

return {
    INNER_INCARNATE_FLAT_DAMAGE_PER_LEVEL = INNER_INCARNATE_FLAT_DAMAGE_PER_LEVEL,
    INNER_INCARNATE_PASSIVE_SHADOW_LEVEL = INNER_INCARNATE_PASSIVE_SHADOW_LEVEL,
    INNER_INCARNATE_LANTERN_SHADOW_LEVEL = INNER_INCARNATE_LANTERN_SHADOW_LEVEL,
    INNER_INCARNATE_DAMAGE_REDUCTION_PER_LEVEL = INNER_INCARNATE_DAMAGE_REDUCTION_PER_LEVEL,
    INNER_INCARNATE_SANITY_REGEN_PER_LEVEL = INNER_INCARNATE_SANITY_REGEN_PER_LEVEL,
    INNER_INCARNATE_SUMMON_SLOT_PENALTY = INNER_INCARNATE_SUMMON_SLOT_PENALTY,
}
