local DREAD_TRIBUTE_BURN_DURATION = 10
local DREAD_TRIBUTE_TICK = 1

local DREAD_TRIBUTE_1_DOT_DPS = 3
local DREAD_TRIBUTE_1_SANITY_COST = 3

-- Visual scale / AoE radius keyed off dying target size.
-- range ≈ scale × (4/3); game uses scale × 1.5 as buffer (3→4.5, 6→9).
local DREAD_TRIBUTE_2_EXPLOSION_SCALE = 3
local DREAD_TRIBUTE_2_EXPLOSION_SCALE_LARGE = 6
local DREAD_TRIBUTE_2_EXPLOSION_RADIUS = 4.5
local DREAD_TRIBUTE_2_EXPLOSION_RADIUS_LARGE = 9
local DREAD_TRIBUTE_2_EXPLOSION_DAMAGE = 30
local DREAD_TRIBUTE_2_EXPLOSION_DAMAGE_LARGE = 80

-- 95% dark tint on borrowed vanilla burn visuals (5% brightness).
local BURN_FX_TINT =
{
    r = .05,
    g = .05,
    b = .05,
    a = 1,
}

local DREAD_TRIBUTE_1_DOT_PCT = 2
local DREAD_TRIBUTE_1_DOT_PCT_LARGE = 0.3

local DREAD_TRIBUTE_WEAPONS =
{
    multitool_axe_pickaxe = true,
    batbat = true,
    ruins_bat = true,
    nightsword = true,
    rabbitkingspear = true,
    voidcloth_scythe = true,
    voidcloth_boomerang = true,
    shadow_battleaxe = true,
    shieldofterror = true,
}

return {
    DREAD_TRIBUTE_BURN_DURATION = DREAD_TRIBUTE_BURN_DURATION,
    DREAD_TRIBUTE_TICK = DREAD_TRIBUTE_TICK,
    DREAD_TRIBUTE_1_DOT_DPS = DREAD_TRIBUTE_1_DOT_DPS,
    DREAD_TRIBUTE_1_SANITY_COST = DREAD_TRIBUTE_1_SANITY_COST,
    DREAD_TRIBUTE_1_DOT_PCT = DREAD_TRIBUTE_1_DOT_PCT,
    DREAD_TRIBUTE_1_DOT_PCT_LARGE = DREAD_TRIBUTE_1_DOT_PCT_LARGE,
    DREAD_TRIBUTE_2_EXPLOSION_SCALE = DREAD_TRIBUTE_2_EXPLOSION_SCALE,
    DREAD_TRIBUTE_2_EXPLOSION_SCALE_LARGE = DREAD_TRIBUTE_2_EXPLOSION_SCALE_LARGE,
    DREAD_TRIBUTE_2_EXPLOSION_RADIUS = DREAD_TRIBUTE_2_EXPLOSION_RADIUS,
    DREAD_TRIBUTE_2_EXPLOSION_RADIUS_LARGE = DREAD_TRIBUTE_2_EXPLOSION_RADIUS_LARGE,
    DREAD_TRIBUTE_2_EXPLOSION_DAMAGE = DREAD_TRIBUTE_2_EXPLOSION_DAMAGE,
    DREAD_TRIBUTE_2_EXPLOSION_DAMAGE_LARGE = DREAD_TRIBUTE_2_EXPLOSION_DAMAGE_LARGE,
    BURN_FX_TINT = BURN_FX_TINT,
    DREAD_TRIBUTE_WEAPONS = DREAD_TRIBUTE_WEAPONS,
}
