-- =============================================================================
-- Constants
-- =============================================================================

local SHADOW_RELIQUARY_SPELL = "SHADOW_RELIQUARY"
local SHADOW_RELIQUARY_DURABILITY_COST_PCT = .20
local SHADOW_RELIQUARY_SANITY_COST = 40 -- flat, no Dark Scholar / Measured Invocation discount
local SHADOW_RELIQUARY_COOLDOWN_ID = "shadow_reliquary"
local SHADOW_RELIQUARY_COOLDOWN_TIME = 180 -- starts when deactivate finishes
local SHADOW_RELIQUARY_ICON_SCALE = .72
local SHADOW_RELIQUARY_ICON_RADIUS = 20
local SHADOW_RELIQUARY_ACTIVE_TAG = "shadow_reliquary_active"

local SHADOW_RELIQUARY_RETICULE_SCALE = 1.3 -- placement reticule only
local SHADOW_RELIQUARY_RETICULE_ANIM = "s"
local SHADOW_RELIQUARY_CAST_RANGE = 12

local SHADOW_RELIQUARY_VISUAL_SCALE = 1
local SHADOW_RELIQUARY_TINT = .15 -- base winch: 85% black
local SHADOW_RELIQUARY_CHEST_TINT = .15 -- legacy default; per-tier tint in TIER_CONFIG
-- Winch draws above chest/codex when stacked at the same point.
local SHADOW_RELIQUARY_WINCH_FINAL_OFFSET = 2
local SHADOW_RELIQUARY_STACKED_FINAL_OFFSET = 1

local function HeavyCarryWalkSpeedMult(penalty_factor)
    local heavy = TUNING.HEAVY_SPEED_MULT or .15
    local mult = 1 - (1 - heavy) * (penalty_factor or 1)
    -- DST equippable walkspeedmult: max .01 precision (inventoryitem_replica assert).
    return math.floor(mult * 100 + .5) / 100
end

-- Wait for sanity_raise to finish (shadow_pillar: pre at 8f, pillar at 15f after FX).
local SHADOW_RELIQUARY_SHADOW_INTRO_DELAY = 15 * FRAMES

-- reticule_s2 was 2.5; slightly larger so edge drops near the winch still suck.
local SHADOW_RELIQUARY_SUCK_RADIUS = 3
local SHADOW_RELIQUARY_SUCK_TIME = 10 * FRAMES
local SHADOW_RELIQUARY_SCAN_PERIOD = 1
-- Extra reach when the chest is dropped from the body (drop point can sit outside the winch).
local SHADOW_RELIQUARY_DROP_ABSORB_PAD = 1

-- Codex Umbra recharge at the winch (waxwelljournal on ground).
local SHADOW_RELIQUARY_CODEX_PREFAB = "waxwelljournal"
local SHADOW_RELIQUARY_CODEX_REPAIR_RATE = .03 -- 3% max fuel per second while docked
local SHADOW_RELIQUARY_CODEX_BUSY_TAG = "waxwell_reliquary_codex_busy"
local SHADOW_RELIQUARY_CODEX_RIFT_BUSY_TAG = "waxwell_reliquary_codex_rift_busy"
local SHADOW_RELIQUARY_LOOT_FLING_XZ_SPREAD = .4

local SHADOW_RELIQUARY_CODEX_RELEASE_SPEED_MIN = 10.5
local SHADOW_RELIQUARY_CODEX_RELEASE_SPEED_MAX = 17.5
local SHADOW_RELIQUARY_CODEX_RELEASE_Y_MIN = 2.5
local SHADOW_RELIQUARY_CODEX_RELEASE_Y_MAX = 5
local SHADOW_RELIQUARY_CODEX_DOCK_Y_OFFSET = .25
local SHADOW_RELIQUARY_CODEX_DOCK_RAISE_TIME = .35

-- Wrong-owner chest placed at a winch is pushed away instead of being absorbed.
local SHADOW_RELIQUARY_CHEST_BOUNCE_SPEED = 4
local SHADOW_RELIQUARY_CHEST_BOUNCE_PAD = 2
local SHADOW_RELIQUARY_CHEST_BOUNCE_COOLDOWN = 1

-- Point placement clearance (winch is a single point, not a big disc like FE).
local SHADOW_RELIQUARY_PLACEMENT_CLEARANCE = 1.25
local SHADOW_RELIQUARY_BLOCKER_PAD = 1.5

-- Polar spawn from base: random angle + distance in [min, max], then expand rings.
local SHADOW_RELIQUARY_CHEST_SPAWN_ATTEMPTS = 64 -- legacy alias for preferred attempts
local SHADOW_RELIQUARY_CHEST_SPAWN_PREFERRED_ATTEMPTS = 64
local SHADOW_RELIQUARY_CHEST_SPAWN_RING_ATTEMPTS = 16
local SHADOW_RELIQUARY_CHEST_SPAWN_EXPAND_STEP = 25
local SHADOW_RELIQUARY_CHEST_SPAWN_MAX_BEYOND = 250
-- large has no max_dist; first pass searches [min, min + band], then expands to absolute cap.
local SHADOW_RELIQUARY_CHEST_LARGE_SPAWN_PREFERRED_BAND = 200
local SHADOW_RELIQUARY_CHEST_SPAWN_ABSOLUTE_MAX = 1500

-- Distance rings from the reliquary base (world units).
local SHADOW_RELIQUARY_CHEST_SMALL_MIN_DIST = 100
local SHADOW_RELIQUARY_CHEST_SMALL_MAX_DIST = 200
local SHADOW_RELIQUARY_CHEST_MEDIUM_MIN_DIST = 200
local SHADOW_RELIQUARY_CHEST_MEDIUM_MAX_DIST = 300
local SHADOW_RELIQUARY_CHEST_LARGE_MIN_DIST = 500

-- Minimum center-to-center gap between SSC chests (may be close, not stacked).
local SHADOW_RELIQUARY_CHEST_SPAWN_MIN_SEP = 1

local SHADOW_RELIQUARY_CHEST_TIER_ORDER = { "small", "medium", "large" }

local SHADOW_RELIQUARY_CHEST_TIER_CONFIG =
{
    small =
    {
        prefab = "waxwell_shadow_sunken_chest_small",
        spawn_period = TUNING.TOTAL_DAY_TIME * 3,
        lifetime = TUNING.TOTAL_DAY_TIME * 1,
        scale = .8,
        carry_penalty = .8, -- 80% of vanilla heavy slowdown (faster than large)
        tint_r = .1,
        tint_g = .1,
        tint_b = .1,
        mapicon = "ssc_map_chest_small.png",
        loot_min = 2,
        loot_max = 3,
        loot =
        {
            "goldnugget", "goldnugget", "goldnugget",
            "nitre", "nitre", "nitre",
            "saltrock", "saltrock",
            "flint", "flint",
        },
        min_dist = SHADOW_RELIQUARY_CHEST_SMALL_MIN_DIST,
        max_dist = SHADOW_RELIQUARY_CHEST_SMALL_MAX_DIST,
    },
    medium =
    {
        prefab = "waxwell_shadow_sunken_chest_medium",
        spawn_period = TUNING.TOTAL_DAY_TIME * 5,
        lifetime = TUNING.TOTAL_DAY_TIME * 2,
        scale = .9,
        carry_penalty = .9,
        tint_r = .24,
        tint_g = .25,
        tint_b = .32,
        mapicon = "ssc_map_chest_medium.png",
        loot_min = 3,
        loot_max = 5,
        loot =
        {
            "goldnugget", "goldnugget",
            "saltrock", "saltrock",
            "nitre",
            "thulecite_pieces", "thulecite_pieces",
            "redgem", "bluegem", "purplegem", "yellowgem", "orangegem", "greengem",
        },
        min_dist = SHADOW_RELIQUARY_CHEST_MEDIUM_MIN_DIST,
        max_dist = SHADOW_RELIQUARY_CHEST_MEDIUM_MAX_DIST,
    },
    large =
    {
        prefab = "waxwell_shadow_sunken_chest_large",
        spawn_period = TUNING.TOTAL_DAY_TIME * 10,
        lifetime = TUNING.TOTAL_DAY_TIME * 3,
        scale = 1,
        carry_penalty = 1,
        tint_r = .22,
        tint_g = .04,
        tint_b = .04,
        mapicon = "ssc_map_chest_large.png",
        loot_min = 5,
        loot_max = 7,
        loot =
        {
            "thulecite_pieces", "thulecite_pieces", "thulecite_pieces", "thulecite_pieces",
            "redgem", "bluegem", "purplegem", "yellowgem", "orangegem", "greengem",
            "goldnugget", "saltrock",
        },
        min_dist = SHADOW_RELIQUARY_CHEST_LARGE_MIN_DIST,
    },
}

-- Legacy single-timer defaults (medium tier).
local SHADOW_RELIQUARY_CHEST_SPAWN_PERIOD = SHADOW_RELIQUARY_CHEST_TIER_CONFIG.medium.spawn_period
local SHADOW_RELIQUARY_CHEST_LIFETIME = SHADOW_RELIQUARY_CHEST_TIER_CONFIG.medium.lifetime

local SHADOW_RELIQUARY_SMASH_DURATION = 4
local SHADOW_RELIQUARY_SMASH_START_INTERVAL = .55
local SHADOW_RELIQUARY_SMASH_END_INTERVAL = .12

local SHADOW_RELIQUARY_DEACTIVATE_DELAY = .2 -- brief fx beat before base is removed

local SHADOW_RELIQUARY_PLACEHOLDER_LOOT =
{
    "goldnugget", "goldnugget",
    "saltrock", "saltrock",
    "nitre",
    "thulecite_pieces",
    "redgem", "bluegem", "purplegem", "yellowgem", "orangegem", "greengem",
}
local SHADOW_RELIQUARY_LOOT_MIN_COUNT = 3
local SHADOW_RELIQUARY_LOOT_MAX_COUNT = 5
-- Scatter loot sideways (a bit farther than "near pile", still readable on screen).
local SHADOW_RELIQUARY_LOOT_FLING_SPEED_MIN = 10.5
local SHADOW_RELIQUARY_LOOT_FLING_SPEED_MAX = 18
local SHADOW_RELIQUARY_LOOT_FLING_Y_MIN = 5
local SHADOW_RELIQUARY_LOOT_FLING_Y_MAX = 8.5

return {
    SHADOW_RELIQUARY_SPELL = SHADOW_RELIQUARY_SPELL,
    SHADOW_RELIQUARY_DURABILITY_COST_PCT = SHADOW_RELIQUARY_DURABILITY_COST_PCT,
    SHADOW_RELIQUARY_SANITY_COST = SHADOW_RELIQUARY_SANITY_COST,
    SHADOW_RELIQUARY_COOLDOWN_ID = SHADOW_RELIQUARY_COOLDOWN_ID,
    SHADOW_RELIQUARY_COOLDOWN_TIME = SHADOW_RELIQUARY_COOLDOWN_TIME,
    SHADOW_RELIQUARY_ICON_SCALE = SHADOW_RELIQUARY_ICON_SCALE,
    SHADOW_RELIQUARY_ICON_RADIUS = SHADOW_RELIQUARY_ICON_RADIUS,
    SHADOW_RELIQUARY_ACTIVE_TAG = SHADOW_RELIQUARY_ACTIVE_TAG,
    SHADOW_RELIQUARY_RETICULE_SCALE = SHADOW_RELIQUARY_RETICULE_SCALE,
    SHADOW_RELIQUARY_RETICULE_ANIM = SHADOW_RELIQUARY_RETICULE_ANIM,
    SHADOW_RELIQUARY_CAST_RANGE = SHADOW_RELIQUARY_CAST_RANGE,
    SHADOW_RELIQUARY_VISUAL_SCALE = SHADOW_RELIQUARY_VISUAL_SCALE,
    SHADOW_RELIQUARY_TINT = SHADOW_RELIQUARY_TINT,
    SHADOW_RELIQUARY_CHEST_TINT = SHADOW_RELIQUARY_CHEST_TINT,
    SHADOW_RELIQUARY_WINCH_FINAL_OFFSET = SHADOW_RELIQUARY_WINCH_FINAL_OFFSET,
    SHADOW_RELIQUARY_STACKED_FINAL_OFFSET = SHADOW_RELIQUARY_STACKED_FINAL_OFFSET,
    SHADOW_RELIQUARY_SHADOW_INTRO_DELAY = SHADOW_RELIQUARY_SHADOW_INTRO_DELAY,
    SHADOW_RELIQUARY_SUCK_RADIUS = SHADOW_RELIQUARY_SUCK_RADIUS,
    SHADOW_RELIQUARY_SUCK_TIME = SHADOW_RELIQUARY_SUCK_TIME,
    SHADOW_RELIQUARY_SCAN_PERIOD = SHADOW_RELIQUARY_SCAN_PERIOD,
    SHADOW_RELIQUARY_DROP_ABSORB_PAD = SHADOW_RELIQUARY_DROP_ABSORB_PAD,
    SHADOW_RELIQUARY_CODEX_PREFAB = SHADOW_RELIQUARY_CODEX_PREFAB,
    SHADOW_RELIQUARY_CODEX_REPAIR_RATE = SHADOW_RELIQUARY_CODEX_REPAIR_RATE,
    SHADOW_RELIQUARY_CODEX_BUSY_TAG = SHADOW_RELIQUARY_CODEX_BUSY_TAG,
    SHADOW_RELIQUARY_CODEX_RIFT_BUSY_TAG = SHADOW_RELIQUARY_CODEX_RIFT_BUSY_TAG,
    SHADOW_RELIQUARY_CODEX_RELEASE_SPEED_MIN = SHADOW_RELIQUARY_CODEX_RELEASE_SPEED_MIN,
    SHADOW_RELIQUARY_CODEX_RELEASE_SPEED_MAX = SHADOW_RELIQUARY_CODEX_RELEASE_SPEED_MAX,
    SHADOW_RELIQUARY_CODEX_RELEASE_Y_MIN = SHADOW_RELIQUARY_CODEX_RELEASE_Y_MIN,
    SHADOW_RELIQUARY_CODEX_RELEASE_Y_MAX = SHADOW_RELIQUARY_CODEX_RELEASE_Y_MAX,
    SHADOW_RELIQUARY_CODEX_DOCK_Y_OFFSET = SHADOW_RELIQUARY_CODEX_DOCK_Y_OFFSET,
    SHADOW_RELIQUARY_CODEX_DOCK_RAISE_TIME = SHADOW_RELIQUARY_CODEX_DOCK_RAISE_TIME,
    SHADOW_RELIQUARY_CHEST_BOUNCE_SPEED = SHADOW_RELIQUARY_CHEST_BOUNCE_SPEED,
    SHADOW_RELIQUARY_CHEST_BOUNCE_PAD = SHADOW_RELIQUARY_CHEST_BOUNCE_PAD,
    SHADOW_RELIQUARY_CHEST_BOUNCE_COOLDOWN = SHADOW_RELIQUARY_CHEST_BOUNCE_COOLDOWN,
    SHADOW_RELIQUARY_PLACEMENT_CLEARANCE = SHADOW_RELIQUARY_PLACEMENT_CLEARANCE,
    SHADOW_RELIQUARY_BLOCKER_PAD = SHADOW_RELIQUARY_BLOCKER_PAD,
    SHADOW_RELIQUARY_CHEST_SPAWN_ATTEMPTS = SHADOW_RELIQUARY_CHEST_SPAWN_ATTEMPTS,
    SHADOW_RELIQUARY_CHEST_SPAWN_PREFERRED_ATTEMPTS = SHADOW_RELIQUARY_CHEST_SPAWN_PREFERRED_ATTEMPTS,
    SHADOW_RELIQUARY_CHEST_SPAWN_RING_ATTEMPTS = SHADOW_RELIQUARY_CHEST_SPAWN_RING_ATTEMPTS,
    SHADOW_RELIQUARY_CHEST_SPAWN_EXPAND_STEP = SHADOW_RELIQUARY_CHEST_SPAWN_EXPAND_STEP,
    SHADOW_RELIQUARY_CHEST_SPAWN_MAX_BEYOND = SHADOW_RELIQUARY_CHEST_SPAWN_MAX_BEYOND,
    SHADOW_RELIQUARY_CHEST_LARGE_SPAWN_PREFERRED_BAND = SHADOW_RELIQUARY_CHEST_LARGE_SPAWN_PREFERRED_BAND,
    SHADOW_RELIQUARY_CHEST_SPAWN_ABSOLUTE_MAX = SHADOW_RELIQUARY_CHEST_SPAWN_ABSOLUTE_MAX,
    SHADOW_RELIQUARY_CHEST_SPAWN_MIN_SEP = SHADOW_RELIQUARY_CHEST_SPAWN_MIN_SEP,
    SHADOW_RELIQUARY_CHEST_SPAWN_PERIOD = SHADOW_RELIQUARY_CHEST_SPAWN_PERIOD,
    SHADOW_RELIQUARY_CHEST_LIFETIME = SHADOW_RELIQUARY_CHEST_LIFETIME,
    SHADOW_RELIQUARY_CHEST_TIER_ORDER = SHADOW_RELIQUARY_CHEST_TIER_ORDER,
    SHADOW_RELIQUARY_CHEST_TIER_CONFIG = SHADOW_RELIQUARY_CHEST_TIER_CONFIG,
    SHADOW_RELIQUARY_CHEST_SMALL_MIN_DIST = SHADOW_RELIQUARY_CHEST_SMALL_MIN_DIST,
    SHADOW_RELIQUARY_CHEST_SMALL_MAX_DIST = SHADOW_RELIQUARY_CHEST_SMALL_MAX_DIST,
    SHADOW_RELIQUARY_CHEST_MEDIUM_MIN_DIST = SHADOW_RELIQUARY_CHEST_MEDIUM_MIN_DIST,
    SHADOW_RELIQUARY_CHEST_MEDIUM_MAX_DIST = SHADOW_RELIQUARY_CHEST_MEDIUM_MAX_DIST,
    SHADOW_RELIQUARY_CHEST_LARGE_MIN_DIST = SHADOW_RELIQUARY_CHEST_LARGE_MIN_DIST,
    SHADOW_RELIQUARY_SMASH_DURATION = SHADOW_RELIQUARY_SMASH_DURATION,
    SHADOW_RELIQUARY_SMASH_START_INTERVAL = SHADOW_RELIQUARY_SMASH_START_INTERVAL,
    SHADOW_RELIQUARY_SMASH_END_INTERVAL = SHADOW_RELIQUARY_SMASH_END_INTERVAL,
    SHADOW_RELIQUARY_DEACTIVATE_DELAY = SHADOW_RELIQUARY_DEACTIVATE_DELAY,
    SHADOW_RELIQUARY_PLACEHOLDER_LOOT = SHADOW_RELIQUARY_PLACEHOLDER_LOOT,
    SHADOW_RELIQUARY_LOOT_MIN_COUNT = SHADOW_RELIQUARY_LOOT_MIN_COUNT,
    SHADOW_RELIQUARY_LOOT_MAX_COUNT = SHADOW_RELIQUARY_LOOT_MAX_COUNT,
    SHADOW_RELIQUARY_LOOT_FLING_SPEED_MIN = SHADOW_RELIQUARY_LOOT_FLING_SPEED_MIN,
    SHADOW_RELIQUARY_LOOT_FLING_SPEED_MAX = SHADOW_RELIQUARY_LOOT_FLING_SPEED_MAX,
    SHADOW_RELIQUARY_LOOT_FLING_Y_MIN = SHADOW_RELIQUARY_LOOT_FLING_Y_MIN,
    SHADOW_RELIQUARY_LOOT_FLING_Y_MAX = SHADOW_RELIQUARY_LOOT_FLING_Y_MAX,
    SHADOW_RELIQUARY_LOOT_FLING_XZ_SPREAD = SHADOW_RELIQUARY_LOOT_FLING_XZ_SPREAD,
    HeavyCarryWalkSpeedMult = HeavyCarryWalkSpeedMult,
}
