-- Domain Expansion constants
local DOMAIN_EXPANSION_SPELL = "DOMAIN_EXPANSION"
local DOMAIN_EXPANSION_DURABILITY_COST_PCT = .20
local DOMAIN_EXPANSION_COOLDOWN_ID = "domain_expansion"
local DOMAIN_EXPANSION_COOLDOWN_TIME = 3 * 60
local DOMAIN_EXPANSION_ICON_SCALE = .72
local DOMAIN_EXPANSION_ICON_RADIUS = 20
local DOMAIN_EXPANSION_ACTIVE_OVERLAY_PERCENT = 1
local DOMAIN_EXPANSION_ACTIVE_TAG = "domain_expansion_active"
local DOMAIN_EXPANSION_RADIUS = 8
local DOMAIN_EXPANSION_RETICULE_SCALE = 1
local DOMAIN_EXPANSION_BARRIER_PILLAR_COUNT = 28
local DOMAIN_EXPANSION_BARRIER_BAND = .55
local DOMAIN_EXPANSION_PILLAR_WARNING_SANITY = .10
local DOMAIN_EXPANSION_SANITY_CAST_MIN = 50
local DOMAIN_EXPANSION_KILL_SANITY_SMALL = 5
local DOMAIN_EXPANSION_KILL_SANITY_LARGE = 30
local DOMAIN_EXPANSION_SPIKE_COUNT = 20
local DOMAIN_EXPANSION_SPIKE_EDGE_PADDING = 1.25
local DOMAIN_EXPANSION_SPIKE_MIN_SPACING = 1.75
local DOMAIN_EXPANSION_SPIKE_FREEZE_PERCENT = .82
local DOMAIN_EXPANSION_SPEED_MULT = 1.20
local DOMAIN_EXPANSION_SPEED_KEY = "waxwell_domain_expansion_speed"

-- Imperial Regalia outfit (merged into Domain Expansion — internal outfit/drain constants)
local IMPERIAL_REGALIA_SPELL = "IMPERIAL_REGALIA"
local IMPERIAL_REGALIA_DURABILITY_COST_PCT = .20
local IMPERIAL_REGALIA_COOLDOWN_ID = "imperial_regalia"
local IMPERIAL_REGALIA_COOLDOWN_TIME = 3 * 60
local IMPERIAL_REGALIA_ICON_SCALE = .72
local IMPERIAL_REGALIA_ICON_RADIUS = 58
local IMPERIAL_REGALIA_ACTIVE_OVERLAY_PERCENT = 1
local IMPERIAL_REGALIA_SANITY_DRAIN_PERIOD = 1
local IMPERIAL_REGALIA_SANITY_DRAIN_START = 1
local IMPERIAL_REGALIA_SANITY_DRAIN_STEP = 1
local IMPERIAL_REGALIA_SANITY_DRAIN_STEP_INTERVAL = 3
local IMPERIAL_REGALIA_SANITY_DRAIN_MAX = 10
local IMPERIAL_REGALIA_SANITY_END_MIN = 1
local IMPERIAL_REGALIA_TAG = "imperial_regalia_buff_active"

local IMPERIAL_REGALIA_TEMP_PREFABS =
{
    [EQUIPSLOTS.HEAD] = "skeletonhat",
    [EQUIPSLOTS.BODY] = "armorskeleton",
    [EQUIPSLOTS.HANDS] = "nightsword",
}

local IMPERIAL_REGALIA_HELMET_COLOURCUBES =
{
    day = "images/colour_cubes/ruins_dark_cc.tex",
    dusk = "images/colour_cubes/ruins_dark_cc.tex",
    night = "images/colour_cubes/ruins_dark_cc.tex",
    full_moon = "images/colour_cubes/ruins_dark_cc.tex",
}

return {
    DOMAIN_EXPANSION_SPELL = DOMAIN_EXPANSION_SPELL,
    DOMAIN_EXPANSION_DURABILITY_COST_PCT = DOMAIN_EXPANSION_DURABILITY_COST_PCT,
    DOMAIN_EXPANSION_COOLDOWN_ID = DOMAIN_EXPANSION_COOLDOWN_ID,
    DOMAIN_EXPANSION_COOLDOWN_TIME = DOMAIN_EXPANSION_COOLDOWN_TIME,
    DOMAIN_EXPANSION_ICON_SCALE = DOMAIN_EXPANSION_ICON_SCALE,
    DOMAIN_EXPANSION_ICON_RADIUS = DOMAIN_EXPANSION_ICON_RADIUS,
    DOMAIN_EXPANSION_ACTIVE_OVERLAY_PERCENT = DOMAIN_EXPANSION_ACTIVE_OVERLAY_PERCENT,
    DOMAIN_EXPANSION_ACTIVE_TAG = DOMAIN_EXPANSION_ACTIVE_TAG,
    DOMAIN_EXPANSION_RADIUS = DOMAIN_EXPANSION_RADIUS,
    DOMAIN_EXPANSION_RETICULE_SCALE = DOMAIN_EXPANSION_RETICULE_SCALE,
    DOMAIN_EXPANSION_BARRIER_PILLAR_COUNT = DOMAIN_EXPANSION_BARRIER_PILLAR_COUNT,
    DOMAIN_EXPANSION_BARRIER_BAND = DOMAIN_EXPANSION_BARRIER_BAND,
    DOMAIN_EXPANSION_PILLAR_WARNING_SANITY = DOMAIN_EXPANSION_PILLAR_WARNING_SANITY,
    DOMAIN_EXPANSION_SANITY_CAST_MIN = DOMAIN_EXPANSION_SANITY_CAST_MIN,
    DOMAIN_EXPANSION_KILL_SANITY_SMALL = DOMAIN_EXPANSION_KILL_SANITY_SMALL,
    DOMAIN_EXPANSION_KILL_SANITY_LARGE = DOMAIN_EXPANSION_KILL_SANITY_LARGE,
    DOMAIN_EXPANSION_SPIKE_COUNT = DOMAIN_EXPANSION_SPIKE_COUNT,
    DOMAIN_EXPANSION_SPIKE_EDGE_PADDING = DOMAIN_EXPANSION_SPIKE_EDGE_PADDING,
    DOMAIN_EXPANSION_SPIKE_MIN_SPACING = DOMAIN_EXPANSION_SPIKE_MIN_SPACING,
    DOMAIN_EXPANSION_SPIKE_FREEZE_PERCENT = DOMAIN_EXPANSION_SPIKE_FREEZE_PERCENT,
    DOMAIN_EXPANSION_SPEED_MULT = DOMAIN_EXPANSION_SPEED_MULT,
    DOMAIN_EXPANSION_SPEED_KEY = DOMAIN_EXPANSION_SPEED_KEY,
    IMPERIAL_REGALIA_SPELL = IMPERIAL_REGALIA_SPELL,
    IMPERIAL_REGALIA_DURABILITY_COST_PCT = IMPERIAL_REGALIA_DURABILITY_COST_PCT,
    IMPERIAL_REGALIA_COOLDOWN_ID = IMPERIAL_REGALIA_COOLDOWN_ID,
    IMPERIAL_REGALIA_COOLDOWN_TIME = IMPERIAL_REGALIA_COOLDOWN_TIME,
    IMPERIAL_REGALIA_ICON_SCALE = IMPERIAL_REGALIA_ICON_SCALE,
    IMPERIAL_REGALIA_ICON_RADIUS = IMPERIAL_REGALIA_ICON_RADIUS,
    IMPERIAL_REGALIA_ACTIVE_OVERLAY_PERCENT = IMPERIAL_REGALIA_ACTIVE_OVERLAY_PERCENT,
    IMPERIAL_REGALIA_SANITY_DRAIN_PERIOD = IMPERIAL_REGALIA_SANITY_DRAIN_PERIOD,
    IMPERIAL_REGALIA_SANITY_DRAIN_START = IMPERIAL_REGALIA_SANITY_DRAIN_START,
    IMPERIAL_REGALIA_SANITY_DRAIN_STEP = IMPERIAL_REGALIA_SANITY_DRAIN_STEP,
    IMPERIAL_REGALIA_SANITY_DRAIN_STEP_INTERVAL = IMPERIAL_REGALIA_SANITY_DRAIN_STEP_INTERVAL,
    IMPERIAL_REGALIA_SANITY_DRAIN_MAX = IMPERIAL_REGALIA_SANITY_DRAIN_MAX,
    IMPERIAL_REGALIA_SANITY_END_MIN = IMPERIAL_REGALIA_SANITY_END_MIN,
    IMPERIAL_REGALIA_TAG = IMPERIAL_REGALIA_TAG,
    IMPERIAL_REGALIA_TEMP_PREFABS = IMPERIAL_REGALIA_TEMP_PREFABS,
    IMPERIAL_REGALIA_HELMET_COLOURCUBES = IMPERIAL_REGALIA_HELMET_COLOURCUBES,
}
