local UMBRAL_RIFT_SPELL = "UMBRAL_RIFT"
-- Match Shadow Sneak / Shadow Prison: base TUNING.SANITY_MED + 5% fuel;
-- LV2 bumps sanity to |UMBRA_SKILL_2_SANITY_COST| and +5% fuel (same as LD II / AB II).
local UMBRAL_RIFT_DURABILITY_COST_PCT = TUNING.WAXWELLJOURNAL_SPELL_COST.SHADOW_TRAP or .05
local UMBRAL_RIFT_SANITY_COST = TUNING.SANITY_MED or 15
local UMBRAL_RIFT_LV2_EXTRA_DURABILITY_COST_PCT = .05
local UMBRAL_RIFT_LV2_EXTRA_SANITY_COST = 5 -- 15 → 20 (same delta as LD II / AB II)
local UMBRAL_RIFT_COOLDOWN_ID = "umbral_rift"
local UMBRAL_RIFT_BASE_COOLDOWN_TIME = 20
local UMBRAL_RIFT_UPGRADED_COOLDOWN_TIME = 20
local UMBRAL_RIFT_BASE_DURATION = 10
local UMBRAL_RIFT_UPGRADED_DURATION = 10
local UMBRAL_RIFT_ICON_SCALE = .62
local UMBRAL_RIFT_ICON_RADIUS = 50
local UMBRAL_RIFT_CAST_RANGE = 20
local UMBRAL_RIFT_RETICULE_SCALE = 1.3
local UMBRAL_RIFT_CLEAR_RADIUS = UMBRAL_RIFT_RETICULE_SCALE * 1.25 -- idle_small work radius
-- หลังวาง mark นับ delay นี้แล้วเริ่ม fade (ไม่ถาวร)
local UMBRAL_RIFT_MARK_LIFETIME = 5
-- ระยะเวลา book anim จุด 2 ก่อนลบ mark หลัง warp สำเร็จ (กัน mark หายก่อน anim จบ)
local UMBRAL_RIFT_WARP_CAST_ANIM_TIME = 52 * FRAMES
local UMBRAL_RIFT_LV2_TRANSFER_RADIUS = 3.5
local UMBRAL_RIFT_LV2_TRANSFER_SEARCH_RADIUS = 4.5
local UMBRAL_RIFT_LV2_SUCTION_TIME = 10 * FRAMES
local UMBRAL_RIFT_LV2_TRAVEL_TIME = 8 * FRAMES
local UMBRAL_RIFT_LV2_STATIC_EMERGE_TIME = 20 * FRAMES
local UMBRAL_RIFT_LV2_EMERGE_SPEED = 4
local UMBRAL_RIFT_LV2_EMERGE_OFFSET = 1.25
local UMBRAL_RIFT_LV2_STATIC_EMERGE_OFFSET = 3.6
local UMBRAL_RIFT_PLACEMENT_CANT_TAGS = { "INLIMBO", "FX", "NOCLICK", "DECOR", "playerghost" }
local UMBRAL_ERUPTION_IMPACT_EXCLUDE_TAGS = { "INLIMBO", "playerghost", "FX", "NOCLICK", "DECOR", "wall", "structure" }
local UMBRAL_RIFT_TRANSFER_EXCLUDE_TAGS = { "INLIMBO", "FX", "NOCLICK", "DECOR", "player", "playerghost", "shadowminion", "companion", "CLASSIFIED" }
local UMBRAL_RIFT_LIVING_TARGET_MUST_TAGS = { "_health" }
local UMBRAL_RIFT_LIVING_TARGET_ONEOF_TAGS = { "smallcreature", "monster", "animal", "character" }
local UMBRAL_RIFT_LIVING_TARGET_PREFAB_BLACKLIST =
{
    walrus = true,
    little_walrus = true,
    beefalo = true,
    babybeefalo = true,
    koalefant_summer = true,
    koalefant_winter = true,
    spiderqueen = true,
}

return {
    UMBRAL_RIFT_SPELL = UMBRAL_RIFT_SPELL,
    UMBRAL_RIFT_DURABILITY_COST_PCT = UMBRAL_RIFT_DURABILITY_COST_PCT,
    UMBRAL_RIFT_SANITY_COST = UMBRAL_RIFT_SANITY_COST,
    UMBRAL_RIFT_LV2_EXTRA_DURABILITY_COST_PCT = UMBRAL_RIFT_LV2_EXTRA_DURABILITY_COST_PCT,
    UMBRAL_RIFT_LV2_EXTRA_SANITY_COST = UMBRAL_RIFT_LV2_EXTRA_SANITY_COST,
    UMBRAL_RIFT_COOLDOWN_ID = UMBRAL_RIFT_COOLDOWN_ID,
    UMBRAL_RIFT_BASE_COOLDOWN_TIME = UMBRAL_RIFT_BASE_COOLDOWN_TIME,
    UMBRAL_RIFT_UPGRADED_COOLDOWN_TIME = UMBRAL_RIFT_UPGRADED_COOLDOWN_TIME,
    UMBRAL_RIFT_BASE_DURATION = UMBRAL_RIFT_BASE_DURATION,
    UMBRAL_RIFT_UPGRADED_DURATION = UMBRAL_RIFT_UPGRADED_DURATION,
    UMBRAL_RIFT_ICON_SCALE = UMBRAL_RIFT_ICON_SCALE,
    UMBRAL_RIFT_ICON_RADIUS = UMBRAL_RIFT_ICON_RADIUS,
    UMBRAL_RIFT_CAST_RANGE = UMBRAL_RIFT_CAST_RANGE,
    UMBRAL_RIFT_RETICULE_SCALE = UMBRAL_RIFT_RETICULE_SCALE,
    UMBRAL_RIFT_CLEAR_RADIUS = UMBRAL_RIFT_CLEAR_RADIUS,
    UMBRAL_RIFT_MARK_LIFETIME = UMBRAL_RIFT_MARK_LIFETIME,
    UMBRAL_RIFT_WARP_CAST_ANIM_TIME = UMBRAL_RIFT_WARP_CAST_ANIM_TIME,
    UMBRAL_RIFT_LV2_TRANSFER_RADIUS = UMBRAL_RIFT_LV2_TRANSFER_RADIUS,
    UMBRAL_RIFT_LV2_TRANSFER_SEARCH_RADIUS = UMBRAL_RIFT_LV2_TRANSFER_SEARCH_RADIUS,
    UMBRAL_RIFT_LV2_SUCTION_TIME = UMBRAL_RIFT_LV2_SUCTION_TIME,
    UMBRAL_RIFT_LV2_TRAVEL_TIME = UMBRAL_RIFT_LV2_TRAVEL_TIME,
    UMBRAL_RIFT_LV2_STATIC_EMERGE_TIME = UMBRAL_RIFT_LV2_STATIC_EMERGE_TIME,
    UMBRAL_RIFT_LV2_EMERGE_SPEED = UMBRAL_RIFT_LV2_EMERGE_SPEED,
    UMBRAL_RIFT_LV2_EMERGE_OFFSET = UMBRAL_RIFT_LV2_EMERGE_OFFSET,
    UMBRAL_RIFT_LV2_STATIC_EMERGE_OFFSET = UMBRAL_RIFT_LV2_STATIC_EMERGE_OFFSET,
    UMBRAL_RIFT_PLACEMENT_CANT_TAGS = UMBRAL_RIFT_PLACEMENT_CANT_TAGS,
    UMBRAL_RIFT_TRANSFER_EXCLUDE_TAGS = UMBRAL_RIFT_TRANSFER_EXCLUDE_TAGS,
    UMBRAL_RIFT_LIVING_TARGET_MUST_TAGS = UMBRAL_RIFT_LIVING_TARGET_MUST_TAGS,
    UMBRAL_RIFT_LIVING_TARGET_ONEOF_TAGS = UMBRAL_RIFT_LIVING_TARGET_ONEOF_TAGS,
    UMBRAL_RIFT_LIVING_TARGET_PREFAB_BLACKLIST = UMBRAL_RIFT_LIVING_TARGET_PREFAB_BLACKLIST,
}