local DARK_SCHOLAR_BASE_SANITY_COST = -TUNING.SANITY_MED
local DARK_SCHOLAR_SANITY_COST = -TUNING.SANITY_SMALL
local DARK_SCHOLAR_SANITY_DISCOUNT = TUNING.SANITY_MED - TUNING.SANITY_SMALL

return {
    DARK_SCHOLAR_BASE_SANITY_COST = DARK_SCHOLAR_BASE_SANITY_COST,
    DARK_SCHOLAR_SANITY_COST = DARK_SCHOLAR_SANITY_COST,
    DARK_SCHOLAR_SANITY_DISCOUNT = DARK_SCHOLAR_SANITY_DISCOUNT,
}
