local SHADOW_STALKER_SPELL = "SHADOW_STALKER"
local SHADOW_STALKER_DURABILITY_COST_PCT = .20
local SHADOW_STALKER_COOLDOWN_ID = "shadow_stalker"
-- cooldown changed to 3 minutes
local SHADOW_STALKER_COOLDOWN_TIME = 3 * 60
local SHADOW_STALKER_ICON_SCALE = .6
local SHADOW_STALKER_ICON_RADIUS = 50
local SHADOW_STALKER_ACTIVE_OVERLAY_PERCENT = 1
local SHADOW_STALKER_ACTIVE_TAG = "shadow_stalker_spell_active"
local SHADOW_STALKER_LIFETIME_TIMER = "shadow_stalker_lifetime"
local SHADOW_STALKER_RETICULE_SCALE = 1.75
local SHADOW_STALKER_CAST_RANGE = 12

return {
    SHADOW_STALKER_SPELL = SHADOW_STALKER_SPELL,
    SHADOW_STALKER_DURABILITY_COST_PCT = SHADOW_STALKER_DURABILITY_COST_PCT,
    SHADOW_STALKER_COOLDOWN_ID = SHADOW_STALKER_COOLDOWN_ID,
    SHADOW_STALKER_COOLDOWN_TIME = SHADOW_STALKER_COOLDOWN_TIME,
    SHADOW_STALKER_ICON_SCALE = SHADOW_STALKER_ICON_SCALE,
    SHADOW_STALKER_ICON_RADIUS = SHADOW_STALKER_ICON_RADIUS,
    SHADOW_STALKER_ACTIVE_OVERLAY_PERCENT = SHADOW_STALKER_ACTIVE_OVERLAY_PERCENT,
    SHADOW_STALKER_ACTIVE_TAG = SHADOW_STALKER_ACTIVE_TAG,
    SHADOW_STALKER_LIFETIME_TIMER = SHADOW_STALKER_LIFETIME_TIMER,
    SHADOW_STALKER_RETICULE_SCALE = SHADOW_STALKER_RETICULE_SCALE,
    SHADOW_STALKER_CAST_RANGE = SHADOW_STALKER_CAST_RANGE,
}
