-- =============================================================================
-- Constants
-- =============================================================================

local FISSURE_ERUPTION_SPELL = "FISSURE_ERUPTION"
local FISSURE_ERUPTION_DURABILITY_COST_PCT = .20
local FISSURE_ERUPTION_SANITY_COST = 40
local FISSURE_ERUPTION_COOLDOWN_ID = "fissure_eruption"
local FISSURE_ERUPTION_COOLDOWN_TIME = 3 * 60
local FISSURE_ERUPTION_DURATION = 20
local FISSURE_ERUPTION_LIFETIME_TIMER = "fissure_eruption_lifetime"
local FISSURE_ERUPTION_ICON_SCALE = .72
local FISSURE_ERUPTION_ICON_RADIUS = 20
local FISSURE_ERUPTION_ACTIVE_TAG = "fissure_eruption_active"

local FISSURE_ERUPTION_RETICULE_SCALE = 8
local FISSURE_ERUPTION_RETICULE_ANIM = "s"
local FISSURE_ERUPTION_WORK_RADIUS = 10 -- scale 8 × 1.25
local FISSURE_ERUPTION_CAST_RANGE = 12

local FISSURE_ERUPTION_VISUAL_SCALE = 2
local FISSURE_ERUPTION_TINT = .10 -- black ~90%
local FISSURE_ERUPTION_COLLAPSE_STAGES = 3
local FISSURE_ERUPTION_COLLAPSE_STAGE_DURATION = 1

local FISSURE_ERUPTION_DAMAGE =
{
    { normal = 15, planar = 5 },
    { normal = 30, planar = 10 },
    { normal = 45, planar = 15 },
}

local FISSURE_ERUPTION_SLOW_MULT = TUNING.CAREFUL_SPEED_MOD or .3
local FISSURE_ERUPTION_SLOW_KEY = "waxwell_fissure_eruption_slow"
local FISSURE_ERUPTION_SLOW_PERIOD = .35

local FISSURE_ERUPTION_SHADOW_FX_DELAY_MIN = .75
local FISSURE_ERUPTION_SHADOW_FX_DELAY_MAX = 2.0
local FISSURE_ERUPTION_SHADOW_FX_COUNT_MIN = 1
local FISSURE_ERUPTION_SHADOW_FX_COUNT_MAX = 3
local FISSURE_ERUPTION_SHADOW_FX_MIN_SPACING = 2.75
local FISSURE_ERUPTION_SHADOW_FX_EDGE_PADDING = 1.35

local FISSURE_ERUPTION_BLOCKER_PAD = 2.5

return {
    FISSURE_ERUPTION_SPELL = FISSURE_ERUPTION_SPELL,
    FISSURE_ERUPTION_DURABILITY_COST_PCT = FISSURE_ERUPTION_DURABILITY_COST_PCT,
    FISSURE_ERUPTION_SANITY_COST = FISSURE_ERUPTION_SANITY_COST,
    FISSURE_ERUPTION_COOLDOWN_ID = FISSURE_ERUPTION_COOLDOWN_ID,
    FISSURE_ERUPTION_COOLDOWN_TIME = FISSURE_ERUPTION_COOLDOWN_TIME,
    FISSURE_ERUPTION_DURATION = FISSURE_ERUPTION_DURATION,
    FISSURE_ERUPTION_LIFETIME_TIMER = FISSURE_ERUPTION_LIFETIME_TIMER,
    FISSURE_ERUPTION_ICON_SCALE = FISSURE_ERUPTION_ICON_SCALE,
    FISSURE_ERUPTION_ICON_RADIUS = FISSURE_ERUPTION_ICON_RADIUS,
    FISSURE_ERUPTION_ACTIVE_TAG = FISSURE_ERUPTION_ACTIVE_TAG,
    FISSURE_ERUPTION_RETICULE_SCALE = FISSURE_ERUPTION_RETICULE_SCALE,
    FISSURE_ERUPTION_RETICULE_ANIM = FISSURE_ERUPTION_RETICULE_ANIM,
    FISSURE_ERUPTION_WORK_RADIUS = FISSURE_ERUPTION_WORK_RADIUS,
    FISSURE_ERUPTION_CAST_RANGE = FISSURE_ERUPTION_CAST_RANGE,
    FISSURE_ERUPTION_VISUAL_SCALE = FISSURE_ERUPTION_VISUAL_SCALE,
    FISSURE_ERUPTION_TINT = FISSURE_ERUPTION_TINT,
    FISSURE_ERUPTION_COLLAPSE_STAGES = FISSURE_ERUPTION_COLLAPSE_STAGES,
    FISSURE_ERUPTION_COLLAPSE_STAGE_DURATION = FISSURE_ERUPTION_COLLAPSE_STAGE_DURATION,
    FISSURE_ERUPTION_DAMAGE = FISSURE_ERUPTION_DAMAGE,
    FISSURE_ERUPTION_SLOW_MULT = FISSURE_ERUPTION_SLOW_MULT,
    FISSURE_ERUPTION_SLOW_KEY = FISSURE_ERUPTION_SLOW_KEY,
    FISSURE_ERUPTION_SLOW_PERIOD = FISSURE_ERUPTION_SLOW_PERIOD,
    FISSURE_ERUPTION_SHADOW_FX_DELAY_MIN = FISSURE_ERUPTION_SHADOW_FX_DELAY_MIN,
    FISSURE_ERUPTION_SHADOW_FX_DELAY_MAX = FISSURE_ERUPTION_SHADOW_FX_DELAY_MAX,
    FISSURE_ERUPTION_SHADOW_FX_COUNT_MIN = FISSURE_ERUPTION_SHADOW_FX_COUNT_MIN,
    FISSURE_ERUPTION_SHADOW_FX_COUNT_MAX = FISSURE_ERUPTION_SHADOW_FX_COUNT_MAX,
    FISSURE_ERUPTION_SHADOW_FX_MIN_SPACING = FISSURE_ERUPTION_SHADOW_FX_MIN_SPACING,
    FISSURE_ERUPTION_SHADOW_FX_EDGE_PADDING = FISSURE_ERUPTION_SHADOW_FX_EDGE_PADDING,
    FISSURE_ERUPTION_BLOCKER_PAD = FISSURE_ERUPTION_BLOCKER_PAD,
}
