local LINGERING_DREAD_1_PANIC_MULT = 1.5
local LINGERING_DREAD_1_TRAP_TAG = "waxwell_lingering_dread_1_trap"
local LINGERING_DREAD_2_TRAP_TAG = "waxwell_lingering_dread_2_trap"
local SHADOW_SNEAK_CURSE_TAG = "waxwell_shadow_sneak_curse"
local SHADOW_SNEAK_CURSE_DAMAGE_TAKEN_MULT = 1.3
local SHADOW_SNEAK_DEBUFF_FX_DEFAULT_MULT = { 1, 1, 1, .5 }
local SHADOW_SNEAK_DEBUFF_FX_DEFAULT_ADD = { 0, 0, 0, 0 }
local SHADOW_SNEAK_DEBUFF_FX_CURSE_MULT = { 1, .4, .45, .8 }
local SHADOW_SNEAK_DEBUFF_FX_CURSE_ADD = { .2, 0, 0, 0 }

return {
    LINGERING_DREAD_1_PANIC_MULT = LINGERING_DREAD_1_PANIC_MULT,
    LINGERING_DREAD_1_TRAP_TAG = LINGERING_DREAD_1_TRAP_TAG,
    LINGERING_DREAD_2_TRAP_TAG = LINGERING_DREAD_2_TRAP_TAG,
    SHADOW_SNEAK_CURSE_TAG = SHADOW_SNEAK_CURSE_TAG,
    SHADOW_SNEAK_CURSE_DAMAGE_TAKEN_MULT = SHADOW_SNEAK_CURSE_DAMAGE_TAKEN_MULT,
    SHADOW_SNEAK_DEBUFF_FX_DEFAULT_MULT = SHADOW_SNEAK_DEBUFF_FX_DEFAULT_MULT,
    SHADOW_SNEAK_DEBUFF_FX_DEFAULT_ADD = SHADOW_SNEAK_DEBUFF_FX_DEFAULT_ADD,
    SHADOW_SNEAK_DEBUFF_FX_CURSE_MULT = SHADOW_SNEAK_DEBUFF_FX_CURSE_MULT,
    SHADOW_SNEAK_DEBUFF_FX_CURSE_ADD = SHADOW_SNEAK_DEBUFF_FX_CURSE_ADD,
}
