STRINGS.SPELLS = STRINGS.SPELLS or {}
local SHADOW_MARKSMAN_SPELL = "SHADOW_MARKSMAN"
local SHADOW_MARKSMAN_ICON_SCALE = .6
local SHADOW_MARKSMAN_ICON_RADIUS = 50
local SHADOW_MARKSMAN_DURABILITY_COST_PCT = .05
local SHADOW_MARKSMAN_ENABLED = true
local SHADOW_MARKSMAN_TINT = { .08, .08, .08, 1 }
local SHADOW_MARKSMAN_DARK_FX_TAG = "shadow_marksman_dark_fx_target"
local SHADOW_MARKSMAN_LV1_TAG = "shadow_marksman_1"
local SHADOW_MARKSMAN_LV2_TAG = "shadow_marksman_2"
local SHADOW_MARKSMAN_SPECIAL_AMMO_COOLDOWN_LV1 = 15
local SHADOW_MARKSMAN_SPECIAL_AMMO_COOLDOWN_LV2 = 10
local SHADOW_MARKSMAN_2_BASE_DURABILITY_COST_PCT = .05
local SHADOW_MARKSMAN_2_DURABILITY_COST_PCT = .10

return {
    SHADOW_MARKSMAN_SPELL = SHADOW_MARKSMAN_SPELL,
    SHADOW_MARKSMAN_ICON_SCALE = SHADOW_MARKSMAN_ICON_SCALE,
    SHADOW_MARKSMAN_ICON_RADIUS = SHADOW_MARKSMAN_ICON_RADIUS,
    SHADOW_MARKSMAN_DURABILITY_COST_PCT = SHADOW_MARKSMAN_DURABILITY_COST_PCT,
    SHADOW_MARKSMAN_ENABLED = SHADOW_MARKSMAN_ENABLED,
    SHADOW_MARKSMAN_TINT = SHADOW_MARKSMAN_TINT,
    SHADOW_MARKSMAN_DARK_FX_TAG = SHADOW_MARKSMAN_DARK_FX_TAG,
    SHADOW_MARKSMAN_LV1_TAG = SHADOW_MARKSMAN_LV1_TAG,
    SHADOW_MARKSMAN_LV2_TAG = SHADOW_MARKSMAN_LV2_TAG,
    SHADOW_MARKSMAN_SPECIAL_AMMO_COOLDOWN_LV1 = SHADOW_MARKSMAN_SPECIAL_AMMO_COOLDOWN_LV1,
    SHADOW_MARKSMAN_SPECIAL_AMMO_COOLDOWN_LV2 = SHADOW_MARKSMAN_SPECIAL_AMMO_COOLDOWN_LV2,
    SHADOW_MARKSMAN_2_BASE_DURABILITY_COST_PCT = SHADOW_MARKSMAN_2_BASE_DURABILITY_COST_PCT,
    SHADOW_MARKSMAN_2_DURABILITY_COST_PCT = SHADOW_MARKSMAN_2_DURABILITY_COST_PCT,
}
