local ABYSSAL_BINDING_1_DURATION_MULT = 1.5
local ABYSSAL_BINDING_1_PILLAR_TAG = "waxwell_abyssal_binding_1_shadow_pillar"
local ABYSSAL_BINDING_1_TARGET_TAG = "waxwell_abyssal_binding_1_shadow_pillar_target"
local ABYSSAL_BINDING_1_SOURCE_FILE = "shadow_pillar.lua"
local ABYSSAL_BINDING_2_DAMAGE = 8
local ABYSSAL_BINDING_2_IMPACT_RADIUS = 1.5
local ABYSSAL_BINDING_2_IMPACT_SEARCH_RADIUS = 6
local ABYSSAL_BINDING_2_IMPACT_DELAY = 10 * FRAMES
local ABYSSAL_BINDING_2_PILLAR_TAG = "waxwell_abyssal_binding_2_shadow_pillar"

return {
    ABYSSAL_BINDING_1_DURATION_MULT = ABYSSAL_BINDING_1_DURATION_MULT,
    ABYSSAL_BINDING_1_PILLAR_TAG = ABYSSAL_BINDING_1_PILLAR_TAG,
    ABYSSAL_BINDING_1_TARGET_TAG = ABYSSAL_BINDING_1_TARGET_TAG,
    ABYSSAL_BINDING_1_SOURCE_FILE = ABYSSAL_BINDING_1_SOURCE_FILE,
    ABYSSAL_BINDING_2_DAMAGE = ABYSSAL_BINDING_2_DAMAGE,
    ABYSSAL_BINDING_2_IMPACT_RADIUS = ABYSSAL_BINDING_2_IMPACT_RADIUS,
    ABYSSAL_BINDING_2_IMPACT_SEARCH_RADIUS = ABYSSAL_BINDING_2_IMPACT_SEARCH_RADIUS,
    ABYSSAL_BINDING_2_IMPACT_DELAY = ABYSSAL_BINDING_2_IMPACT_DELAY,
    ABYSSAL_BINDING_2_PILLAR_TAG = ABYSSAL_BINDING_2_PILLAR_TAG,
}
