local SHADOW_GLUTTONY_FOODTYPE = "SHADOW_GLUTTONY"
local SHADOW_GLUTTONY_SANITY_PER_FUEL = 10
local SHADOW_GLUTTONY_SANITY_PER_HORROR = 20
-- Fraction of any positive HP heal from eating that is redirected to sanity.
local SHADOW_GLUTTONY_HEAL_TO_SANITY_RATIO = 0.5
local SHADOW_GLUTTONY_REGEN_DURATION = 5
local SHADOW_GLUTTONY_REGEN_TICK = 1

return {
    SHADOW_GLUTTONY_FOODTYPE = SHADOW_GLUTTONY_FOODTYPE,
    SHADOW_GLUTTONY_SANITY_PER_FUEL = SHADOW_GLUTTONY_SANITY_PER_FUEL,
    SHADOW_GLUTTONY_SANITY_PER_HORROR = SHADOW_GLUTTONY_SANITY_PER_HORROR,
    SHADOW_GLUTTONY_HEAL_TO_SANITY_RATIO = SHADOW_GLUTTONY_HEAL_TO_SANITY_RATIO,
    SHADOW_GLUTTONY_REGEN_DURATION = SHADOW_GLUTTONY_REGEN_DURATION,
    SHADOW_GLUTTONY_REGEN_TICK = SHADOW_GLUTTONY_REGEN_TICK,
}
