local NIGHTMARE_DOMINION_DAMAGE_BONUS = .30
local NIGHTMARE_DOMINION_DAMAGE_REDUCTION = .30

return {
    NIGHTMARE_DOMINION_DAMAGE_BONUS = NIGHTMARE_DOMINION_DAMAGE_BONUS,
    NIGHTMARE_DOMINION_DAMAGE_REDUCTION = NIGHTMARE_DOMINION_DAMAGE_REDUCTION,
}
