local TIRELESS_SERVANT_1_SPEED = 8
local TIRELESS_SERVANT_1_DURATION_BONUS_PCT = .50
local TIRELESS_SERVANT_1_TAG = "tireless_servant_1_shadow_servant"
local TIRELESS_SERVANT_2_FREE_SPAWN_CHANCE = .33
local TIRELESS_SERVANT_2_BASE_DURABILITY_COST_PCT = .05
local TIRELESS_SERVANT_2_DURABILITY_COST_PCT = .10
local FREE_SHADOW_SERVANT_TAG = "free_shadow_servant"
local SHADOW_MINION_BASE_TINT = 0
local SHADOW_MINION_BASE_ALPHA = .85
local FREE_SHADOW_SERVANT_ADD_TINT = .50
local FREE_SHADOW_SERVANT_TINT_RETRIES = 120

return {
    TIRELESS_SERVANT_1_SPEED = TIRELESS_SERVANT_1_SPEED,
    TIRELESS_SERVANT_1_DURATION_BONUS_PCT = TIRELESS_SERVANT_1_DURATION_BONUS_PCT,
    TIRELESS_SERVANT_1_TAG = TIRELESS_SERVANT_1_TAG,
    TIRELESS_SERVANT_2_FREE_SPAWN_CHANCE = TIRELESS_SERVANT_2_FREE_SPAWN_CHANCE,
    TIRELESS_SERVANT_2_BASE_DURABILITY_COST_PCT = TIRELESS_SERVANT_2_BASE_DURABILITY_COST_PCT,
    TIRELESS_SERVANT_2_DURABILITY_COST_PCT = TIRELESS_SERVANT_2_DURABILITY_COST_PCT,
    FREE_SHADOW_SERVANT_TAG = FREE_SHADOW_SERVANT_TAG,
    SHADOW_MINION_BASE_TINT = SHADOW_MINION_BASE_TINT,
    SHADOW_MINION_BASE_ALPHA = SHADOW_MINION_BASE_ALPHA,
    FREE_SHADOW_SERVANT_ADD_TINT = FREE_SHADOW_SERVANT_ADD_TINT,
    FREE_SHADOW_SERVANT_TINT_RETRIES = FREE_SHADOW_SERVANT_TINT_RETRIES,
}
