local SKILLTREE = STRINGS.SKILLTREE

--//////////////////// Skill Panel Name
SKILLTREE.PANELS.WAXWELL_PUPPETEER = "Puppeteer"
SKILLTREE.PANELS.WAXWELL_UMBRA = "Umbra"
SKILLTREE.PANELS.WAXWELL_SOVEREIGN = "Sovereign"
SKILLTREE.PANELS.WAXWELL_EMPEROR = "Emperor"

--//////////////////// Skill Name (icon atlas order: 5x7, left-to-right, top-to-bottom)
-- Puppeteer
SKILLTREE.NAMES.WAXWELL_FRAGMENTED_MIND = "Fragmented Mind"
SKILLTREE.NAMES.WAXWELL_EXPANDED_DOMINION = "Expanded Dominion"
SKILLTREE.NAMES.WAXWELL_TIRELESS_SERVANT_1 = "Tireless Servant I"
SKILLTREE.NAMES.WAXWELL_TIRELESS_SERVANT_2 = "Tireless Servant II"
SKILLTREE.NAMES.WAXWELL_LETHAL_APPARITION_1 = "Lethal Apparition I"
SKILLTREE.NAMES.WAXWELL_LETHAL_APPARITION_2 = "Lethal Apparition II"
SKILLTREE.NAMES.WAXWELL_SHADOW_LANTERNBEARER_1 = "Shadow Lanternbearer I"
SKILLTREE.NAMES.WAXWELL_SHADOW_LANTERNBEARER_2 = "Shadow Lanternbearer II"
SKILLTREE.NAMES.WAXWELL_SHADOW_MARKSMAN_1 = "Shadow Marksman I"
SKILLTREE.NAMES.WAXWELL_SHADOW_MARKSMAN_2 = "Shadow Marksman II"
-- Umbra
SKILLTREE.NAMES.WAXWELL_DARK_SCHOLAR = "Dark Scholar"
SKILLTREE.NAMES.WAXWELL_MEASURED_INVOCATION = "Measured Invocation"
SKILLTREE.NAMES.WAXWELL_LINGERING_DREAD_1 = "Lingering Dread I"
SKILLTREE.NAMES.WAXWELL_LINGERING_DREAD_2 = "Lingering Dread II"
SKILLTREE.NAMES.WAXWELL_ABYSSAL_BINDING_1 = "Abyssal Binding I"
SKILLTREE.NAMES.WAXWELL_ABYSSAL_BINDING_2 = "Abyssal Binding II"
SKILLTREE.NAMES.WAXWELL_UMBRAL_RIFT_1 = "Umbral Rift I"
SKILLTREE.NAMES.WAXWELL_UMBRAL_RIFT_2 = "Umbral Rift II"
SKILLTREE.NAMES.WAXWELL_ECLIPSE_FALL_1 = "Eclipse Fall I"
SKILLTREE.NAMES.WAXWELL_ECLIPSE_FALL_2 = "Eclipse Fall II"
-- Sovereign
SKILLTREE.NAMES.WAXWELL_ROYAL_COMPOSURE = "Royal Composure"
SKILLTREE.NAMES.WAXWELL_SHADOW_CONJURY = "Shadow Conjury"
SKILLTREE.NAMES.WAXWELL_SHADOW_GLUTTONY = "Shadow Gluttony"
SKILLTREE.NAMES.WAXWELL_NIGHTMARE_DOMINION = "Nightmare Dominion"
SKILLTREE.NAMES.WAXWELL_DREAD_TRIBUTE_1 = "Dread Tribute I"
SKILLTREE.NAMES.WAXWELL_DREAD_TRIBUTE_2 = "Dread Tribute II"
SKILLTREE.NAMES.WAXWELL_MIND_OVER_MATTER = "Mind Over Matter"
SKILLTREE.NAMES.WAXWELL_CHAOS_INOCULATION = "Chaos Inoculation"
SKILLTREE.NAMES.WAXWELL_MINDS_RECOMPENSE = "Mind's Recompense"
SKILLTREE.NAMES.WAXWELL_INNER_INCARNATE = "Inner Incarnate"
-- Emperor
SKILLTREE.NAMES.WAXWELL_SHADOW_STALKER = "Shadow Stalker"
SKILLTREE.NAMES.WAXWELL_DOMAIN_EXPANSION = "Domain Expansion"
SKILLTREE.NAMES.WAXWELL_FISSURE_ERUPTION = "Fissure Eruption"
SKILLTREE.NAMES.WAXWELL_SHADOW_RELIQUARY = "Shadow Reliquary"

--//////////////////// Skill Description (icon atlas order)
-- Puppeteer
SKILLTREE.desc.waxwell_fragmented_mind = "Summon Spells Reduce Sanity Penalty by 5% Less."
SKILLTREE.desc.waxwell_expanded_dominion = "Increases The Maximum Shadow Summon Capacity From 7 to 9 Slots."
SKILLTREE.desc.waxwell_tireless_servant_1 = "\"Shadow Servants\" Move at 8 Speed Instead of 6 And Last 50% Longer."
SKILLTREE.desc.waxwell_tireless_servant_2 = "Summoning a \"Shadow Servant\" Now Has a 33% Chance to Spawn a Second Free One."
SKILLTREE.desc.waxwell_lethal_apparition_1 = "\"Shadow Duelists\" Increases Max Health From 75 to 100 And Last 50% Longer."
SKILLTREE.desc.waxwell_lethal_apparition_2 = "\"Shadow Duelists\" Gain a 25% Chance to Critical Strike For 50% Bonus Damage."
SKILLTREE.desc.waxwell_shadow_lanternbearer_1 = "Unlock Summon Spell \"Shadow Lanternbearer\". Carries a Lantern That Provides Light, Follows a Chosen Nearby Player."
SKILLTREE.desc.waxwell_shadow_lanternbearer_2 = "\"Shadow Lanternbearer\" Periodically Releases 3 Shadow Fireflies While Combat, Then Explode for 12 AoE Damage."
SKILLTREE.desc.waxwell_shadow_marksman_1 = "Unlock Summon Spell \"Shadow Marksman\". Fights With a Slingshot, And Fires Special Ammo Every 15 Seconds."
SKILLTREE.desc.waxwell_shadow_marksman_2 = "\"Shadow Marksman\" Uses Upgraded Special Ammo And Fires Them Every 10 Seconds Instead."
-- Umbra
SKILLTREE.desc.waxwell_dark_scholar = "Magic Spells Cost 5 Less Sanity. \"Eclipse Fall\" Instead Spends 10% Less Sanity While Still Scaling Damage From Full Sanity."
SKILLTREE.desc.waxwell_measured_invocation = "Magic Spells Have a 33% Chance to Not Consume Durability."
SKILLTREE.desc.waxwell_lingering_dread_1 = "Extends The Duration of \"Shadow Sneak\" Panic Effect by 50%."
SKILLTREE.desc.waxwell_lingering_dread_2 = "Panicked Enemies From \"Shadow Sneak\" Take 30% More Damage From All Sources."
SKILLTREE.desc.waxwell_abyssal_binding_1 = "Extends The Duration of \"Shadow Prison\" Immobilization Effect by 50%"
SKILLTREE.desc.waxwell_abyssal_binding_2 = "Each Pillar of \"Shadow Prison\" Deals 8 AoE Damage When It Lands."
SKILLTREE.desc.waxwell_umbral_rift_1 = "Unlock Magic Spell \"Umbral Rift\". Select a Start Point And a Destination Point to Open a Linked Pair of Portals."
SKILLTREE.desc.waxwell_umbral_rift_2 = "When \"Umbral Rift\" is Cast, Both Portals Pull in Nearby Dropped Items, Then Spit Them Out From The Opposite Side."
SKILLTREE.desc.waxwell_eclipse_fall_1 = "Unlock Magic Spell \"Eclipse Fall\". Consumes All Current Sanity When Cast to Call Down Meteors. Each Meteor Deals 7 AoE Damage, Increased by 1% Per Sanity Spent."
SKILLTREE.desc.waxwell_eclipse_fall_2 = "Large Meteor Crashes at The Center For 28 Damage (Sanity Scaling Applies). Spikes Burst in 8 Directions for 3 Damage Each."
-- Sovereign
SKILLTREE.desc.waxwell_royal_composure = "Reduces Sanity Loss From Monster Auras And Darkness by 50%. Killing Certain Shadow Creatures May Yield Extra Nightmare Fuel."
SKILLTREE.desc.waxwell_shadow_conjury = "Add New Recipes for Ephemeral Shadow Tools From Nightmare Fuel. They Fade After a Short Time."
SKILLTREE.desc.waxwell_shadow_gluttony = "Maxwell Can Eat Nightmare Fuel or Pure Horror to Restore Sanity. Half of Any Health Restored From Foods is Redirected to Sanity Instead."
SKILLTREE.desc.waxwell_nightmare_dominion = "Deal 30% More Damage to Normal Shadow Creatures, And Take 30% Less Damage From Them And Charlie."
SKILLTREE.desc.waxwell_dread_tribute_1 = "While Wielding a Shadow Weapon, Attacks Ignite Targets With Shadow Flames, Dealing Damage Over Time."
SKILLTREE.desc.waxwell_dread_tribute_2 = "Enemies That Die While Burning Will Explode, Dealing AoE Damage Nearby."
SKILLTREE.desc.waxwell_mind_over_matter = "All Damage Taken is Redirected to Sanity First. Sanity Regeneration Increases to 10 Per Minute."
SKILLTREE.desc.waxwell_chaos_inoculation = "Health Penalty Reduces Effective Maximum Health to 1. Gain +75 Maximum Sanity That is Not Reduced by Summon Penalties. This Penalty Cannot Be Recovered."
SKILLTREE.desc.waxwell_minds_recompense = "30% of Damage Taken From Attacks is Converted Into Sanity Restored Over 4 Seconds. Environmental Damage Does Not Count."
SKILLTREE.desc.waxwell_inner_incarnate = "Shadow Level Bonuses Affect Maxwell Instead Summon. Gains +1 Shadow Level. Gain Attack Damage, Sanity Regen, Damage Reduction Per Shadow Level. Maximum Summon Capacity is Reduced by 2."
-- Emperor
SKILLTREE.desc.waxwell_shadow_stalker = "Unlock Summon Spell \"Shadow Stalker\". Summon The Ultimate Shadow Servant, Capable of Accepting Tributes to Aawaken Greater Power."
SKILLTREE.desc.waxwell_domain_expansion = "Unlock Magic Spell \"Domain Expansion\". Creates a Domain Field, And Equips a Temporary Regalia Set That Drains Sanity Overtime. Magic And Summoning Will be Restricted."
SKILLTREE.desc.waxwell_fissure_eruption = "Unlock Magic Spell \"Fissure Eruption\". Create a Dark Sinkhole That Damages in Three Pulses And Slows Foes Inside."
SKILLTREE.desc.waxwell_shadow_reliquary = "Unlock Magic Spell \"Shadow Reliquary\". Place a Shadow Winch That Random Summons Shadow Sunken Chests And Can Recharge Your Codex Umbra. Chests Can Put Into The Winch to Unlock."