STRINGS.NAMES.SHADOW_STALKER = "Shadow Stalker"
STRINGS.NAMES.SHADOW_LANTERNBEARER = "Shadow Lanternbearer"
STRINGS.NAMES.SHADOW_MARKSMAN = "Shadow Marksman"
STRINGS.NAMES.SHADOW_STALKER_FEAST_FIREFLY = "Shadow Fireflies"
STRINGS.NAMES.WAXWELL_SHADOW_FIREFLY = "Shadow Fireflies"
STRINGS.NAMES.UMBRAL_RIFT_PORTAL = "Umbral Rift"
STRINGS.NAMES.WAXWELL_SHADOW_SUNKEN_CHEST = "Shadow Sunken Chest"
STRINGS.NAMES.WAXWELL_SHADOW_SUNKEN_CHEST_SMALL = "Small Shadow Sunken Chest"
STRINGS.NAMES.WAXWELL_SHADOW_SUNKEN_CHEST_MEDIUM = "Shadow Sunken Chest"
STRINGS.NAMES.WAXWELL_SHADOW_SUNKEN_CHEST_LARGE = "Large Shadow Sunken Chest"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.WAXWELL_SHADOW_SUNKEN_CHEST = "A sunken treasure, steeped in shadow."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WAXWELL_SHADOW_SUNKEN_CHEST = "Relics from the deep, bound to my winch."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WAXWELL_SHADOW_SUNKEN_CHEST_SMALL = "A sunken treasure, steeped in shadow."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WAXWELL_SHADOW_SUNKEN_CHEST_SMALL = "A modest relic from the deep."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WAXWELL_SHADOW_SUNKEN_CHEST_MEDIUM = "A sunken treasure, steeped in shadow."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WAXWELL_SHADOW_SUNKEN_CHEST_MEDIUM = "Relics from the deep, bound to my winch."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WAXWELL_SHADOW_SUNKEN_CHEST_LARGE = "A sunken treasure, steeped in shadow."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WAXWELL_SHADOW_SUNKEN_CHEST_LARGE = "A heavy trove from the deep, bound to my winch."

STRINGS.SPELLS.SHADOW_LANTERNBEARER = STRINGS.SPELLS.SHADOW_LANTERNBEARER or "Shadow Lanternbearer"

STRINGS.CHARACTERS.WAXWELL.ACTIONFAIL.CASTAOE = STRINGS.CHARACTERS.WAXWELL.ACTIONFAIL.CASTAOE or {}
STRINGS.CHARACTERS.WAXWELL.ACTIONFAIL.CASTAOE.HASPET = STRINGS.CHARACTERS.WAXWELL.ACTIONFAIL.BUILD.HASPET
STRINGS.CHARACTERS.WAXWELL.ACTIONFAIL.CASTAOE.NO_FUEL = "The codex lacks the fuel."
STRINGS.CHARACTERS.WAXWELL.ACTIONFAIL.CASTAOE.NO_SANITY = "My mind isn't steady enough."
STRINGS.CHARACTERS.WAXWELL.ACTIONFAIL.CASTAOE.NO_FUEL_AND_SANITY = "The codex is spent, and my mind unsteady."
STRINGS.CHARACTERS.WAXWELL.ACTIONFAIL.CASTAOE.NO_LANTERN_TARGET = "No one here to serve."
STRINGS.CHARACTERS.WAXWELL.ACTIONFAIL.CASTAOE.NO_LANTERN_NEEDED = "No one here needs my light."

STRINGS.CHARACTERS.GENERIC.ACTIONFAIL.CASTAOE = STRINGS.CHARACTERS.GENERIC.ACTIONFAIL.CASTAOE or {}
STRINGS.CHARACTERS.GENERIC.ACTIONFAIL.CASTAOE.NO_LANTERN_TARGET = STRINGS.CHARACTERS.WAXWELL.ACTIONFAIL.CASTAOE.NO_LANTERN_TARGET
STRINGS.CHARACTERS.GENERIC.ACTIONFAIL.CASTAOE.NO_LANTERN_NEEDED = STRINGS.CHARACTERS.WAXWELL.ACTIONFAIL.CASTAOE.NO_LANTERN_NEEDED